language: generic
sudo: required
services:
    #tell TravisCI to install docker
    - docker

before_install:
    #-t cicd tags image; use instead of image id
    - docker build -t test -f ./Dockerfile.dev .

script:
    - docker run -e CI=true test npm run start