language: node_js
node_js: node
services:
- docker
before_install:
- docker build -t test -f ./Dockerfile.dev .
script:
- docker-compose up
dd:
- openssl aes-256-cbc -K $encrypted_3c84dcdc6bbe_key -iv $encrypted_3c84dcdc6bbe_iv
  -in .env.enc -out .env -d
